### ISSUE TITLE
Mod not gathering snapshots

### ISSUE THREAD

**Issue by Unkind98** [rcav8tr/MoreCityStatistics#2]
Hello, @rcav8tr .

Thank you for making this very good mod. But I got a problem when using Real-Time mod. So, I used this mod with Real-Time mod and expected that snapshots will be taken every noon. I played and passed a few in-game days, but no snapshot has been taken. And the date for the "From" slide always synchronizes with the current in-game date. So, when a new in-game day starts, the range follows the day's date instead of saving a snapshot for in-game yesterday and before. 

PS: I think this mod will be more useful if it takes snapshots every 2 hours instead of once per day (noon). Because I want to compare the data of noon activities with the night ones, like transportation for example. So, I can utilize the transportation budget by cutting off the lines with low-dense passengers.

**Comment by rcav8tr** [comment]
@Unkind98  You are not the first to report that no snapshots are taken with Real Time.  But I can never duplicate the problem myself.  I updated my mod to log some debug info that hopefully will lead me to the cause of the problem with RT.  Please try it again and send me your output_log.txt file.

**Comment by rcav8tr** [comment]
@Unkind98 Thank you for the suggestion of more snapshots per day when RT is enabled.  However, more snapshots per day would require a significant rewrite of parts of the mod that assume snapshots are by date alone, not date and time.  I have no plans to do that right now.

**Comment by Unkind98** [comment]
> @Unkind98 You are not the first to report that no snapshots are taken with Real Time. But I can never duplicate the problem myself. I updated my mod to log some debug info that hopefully will lead me to the cause of the problem with RT. Please try it again and send me your output_log.txt file.

Great, I'll do that.

**Comment by rcav8tr** [comment]
@Unkind98  I updated MCS to allow more frequent snapshots.  As part of that change, the logic for when to take a snapshot is replaced and simplified.  Hopefully, this will also solve the issue with snapshots not being taken when Real Time is enabled.  Please try it again and let me know whether or not you are still having the issue.

**Comment by Unkind98** [comment]
Oh Okay. I really appreciate it. I will try it soon and let you know if some issues are there.

**Comment by rcav8tr** [comment]
> Oh Okay. I really appreciate it. I will try it soon and let you know if some issues are there. And, where output _log.txt is located?

See instructions here for how to find output log file.  You can share your output log file in GitHub.
https://steamcommunity.com/sharedfiles/filedetails/?id=463645931

**Comment by Unkind98** [comment]
[Uploading output_log.txt…]()
Testing with loading existing savegame. No snapshot has been taken. I will test with newgame after this.

**Comment by Unkind98** [comment]
[Uploading output_log.txt…]()
Testing with loading existing savegame. No snapshot has been taken. I will test with newgame after this.

**Comment by Unkind98** [comment]
Testing with loading existing savegame. No snapshot has been taken. I will test with newgame after this.
[output_log.txt](https://github.com/rcav8tr/MoreCityStatistics/files/10211416/output_log.txt)

**Comment by rcav8tr** [comment]
> 

Thanks for the log file.  I see an exception being thrown by MCS that prevents the mod from working.  I will work on fixing it.  Not sure when I will get to it because a new DLC releases tomorrow (Dec 13) and I need to make sure the DLC does not break any of my mods.

**Comment by Unkind98** [comment]
@rcav8tr Your welcome. And this testing with newgame. 
[output_log.txt](https://github.com/rcav8tr/MoreCityStatistics/files/10212817/output_log.txt)

**Comment by Unkind98** [comment]
![20221215150135_1](https://user-images.githubusercontent.com/94144447/207939795-28420efd-6ace-4cce-bed8-45a88c3ff14b.jpg)
Everything works now! The screenshot was taken after the new DLC. Good job!

**Comment by rcav8tr** [comment]
@Unkind98 Thanks for the report.  However I don't know if it worked for you because of the new DLC or it just happened to work this time.  Therefore, the latest version just released includes a fix for the issue (hopefully).  The latest version also includes updates for the new DLC.  I am leaving the issue closed.
